name: Publish Container

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: publication-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: compellio/dcap-web

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
         
      - id: push
        name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: "true"
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
